try{
    async function testFunction(){
        console.log(x)
    }
    testFunction();
}catch(error){
    console.log("Error")
}